# Generated by Django 5.1.7 on 2025-03-20 18:13

import DCVExpert.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=255)),
                ('schedule', models.CharField(max_length=255)),
                ('lesson_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=1550)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(upload_to=DCVExpert.utils.teacher_image_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('curriculumId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DCVExpert.curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=510)),
                ('photo', models.ImageField(upload_to=DCVExpert.utils.course_image_upload_path)),
                ('is_visibil', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('about', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DCVExpert.coursedescription')),
                ('curriculum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DCVExpert.curriculum')),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DCVExpert.price')),
                ('teachers', models.ManyToManyField(to='DCVExpert.teacher')),
            ],
        ),
    ]
