# Generated by Django 5.1.7 on 2025-03-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCVExpert', '0002_courscategory_course_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=255)),
                ('coursName', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Checked', models.BooleanField(default=False)),
            ],
        ),
    ]
